services:
  mysql:
    image: mysql:8.0
    container_name: dac_trung_bo_go-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dac_trung_bo_go
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

#cmd: docker-compose up -d
